variables:
  # To be defined in the pipeline:
  # Azure Resource Manager connection created during pipeline creation
  # azureSubscription: '8b56f7d1-fdee-4bdd-a910-fec4c9c6a79c' (the name may work also)
  # appname (the name of the limestone web app; e.g. app-limestone-dev)

  # Agent VM image name
  vmImageName: 'windows-latest'
  webHostDir: '$(System.DefaultWorkingDirectory)/FunctionApp1'  

stages:
  - stage: 'Limestone_WebApp'
    jobs:
      - job: Deploy
        displayName: 'deploying Web Jobs'
        pool:
          vmimage: $(vmimagename)
        steps:
          #- task: NuGetAuthenticate@0
          #- task: NuGetToolInstaller@1
          #- task: NuGetCommand@2
          #  inputs:
          #    command: 'restore'
          #    restoreSolution: '**/*.sln'
          #    feedsToUse: 'select'
          #    vstsFeed: '695454c5-2fc4-4ea5-8774-f593d5d93f39/55479e6f-d9a4-40f5-ab30-b013555bf1da'
          - task: dotnetcorecli@2
            displayName: 'dotnet build'
            inputs:
              command: 'build'
              projects: ${{ variables.webHostDir }}/*.csproj    
              arguments: --configuration Debug
          - task: DotNetCoreCLI@2
            displayName: 'Publish Namoluk'
            inputs:
              command: publish
              projects: ${{ variables.webHostDir }}/*.csproj
              arguments: --output $(Build.BinariesDirectory)\publish_output
              zipAfterPublish: true
              modifyOutputPath: false
          - task: AzureWebApp@1
            displayName: 'Deploying Namoluk'
            inputs:
              azureSubscription: 'MAIC - TEK Experts CR - v-gengon Group#1 (90d7af21-b3a1-4bf8-a149-8e1fcc47e337)'
              appType: 'webApp'
              appName: 'FunctionApp-2204290040005774'
              package: '$(Build.BinariesDirectory)/**/*.zip'
              deploymentMethod: auto